//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBXTools.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConversionAPI_MTF_TBXHandlersResourcesExpected {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConversionAPI_MTF_TBXHandlersResourcesExpected() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TBXTools.Test.ConversionAPI.MTF.TBXHandlersResourcesExpected", typeof(ConversionAPI_MTF_TBXHandlersResourcesExpected).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;conceptGrp&gt;
        ///        &lt;concept&gt;1&lt;/concept&gt;
        ///        &lt;transacGrp&gt;
        ///            &lt;transac type=&quot;origination&quot;&gt;mwetzel&lt;/transac&gt;
        ///            &lt;date&gt;2009-05-05T00:00:00&lt;/date&gt;
        ///        &lt;/transacGrp&gt;
        ///        &lt;transacGrp&gt;
        ///            &lt;transac type=&quot;modification&quot;&gt;mwetzel&lt;/transac&gt;
        ///            &lt;date&gt;2009-05-05T00:00:00&lt;/date&gt;
        ///        &lt;/transacGrp&gt;
        ///        &lt;languageGrp&gt;
        ///            &lt;language type=&quot;German&quot; lang=&quot;DE&quot; /&gt;
        ///            &lt;termGrp&gt;
        ///                &lt;term&gt;Schnittstelle&lt;/term&gt;
        ///                &lt;transacGrp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string conceptEntry {
            get {
                return ResourceManager.GetString("conceptEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;date&gt;2009-05-05T00:00:00&lt;/date&gt;.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;descrip type=&quot;Subject&quot;&gt;security services;European Commission&lt;/descrip&gt;.
        /// </summary>
        internal static string descrip {
            get {
                return ResourceManager.GetString("descrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;languageGrp&gt;
        ///            &lt;language type=&quot;English&quot; lang=&quot;EN&quot; /&gt;
        ///            &lt;termGrp&gt;
        ///                &lt;term&gt;interface&lt;/term&gt;
        ///                &lt;transacGrp&gt;
        ///                    &lt;transac type=&quot;origination&quot;&gt;poweruser&lt;/transac&gt;
        ///                    &lt;date&gt;2006-12-08T00:00:00&lt;/date&gt;
        ///                &lt;/transacGrp&gt;
        ///                &lt;transacGrp&gt;
        ///                    &lt;transac type=&quot;modification&quot;&gt;poweruser&lt;/transac&gt;
        ///                    &lt;date&gt;2006-12-08T00:00:00&lt;/date&gt;
        ///                &lt;/transacGrp&gt;
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string langSec {
            get {
                return ResourceManager.GetString("langSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;descrip type=&quot;Note&quot;&gt;Another name for an open star cluster. They are often
        ///                        termed Galactic Clusters because they are found mainly in the plane of our
        ///                        galaxy. If you were to view our galaxy from afar, you would find that all
        ///                        the open/galactic clusters lie within the spiral arms of the
        ///                        galaxy.&lt;/descrip&gt;.
        /// </summary>
        internal static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;term&gt;méthodologie prouvée&lt;/term&gt;.
        /// </summary>
        internal static string term {
            get {
                return ResourceManager.GetString("term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;descrip type=&quot;Part of Speech&quot;&gt;noun&lt;/descrip&gt;.
        /// </summary>
        internal static string termNote {
            get {
                return ResourceManager.GetString("termNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;termNoteGrp&gt;
        ///                    &lt;termNote type=&quot;partOfSpeech&quot;&gt;noun&lt;/termNote&gt;
        ///                &lt;/termNoteGrp&gt;.
        /// </summary>
        internal static string termNote_toGroupify {
            get {
                return ResourceManager.GetString("termNote_toGroupify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;termGrp&gt;
        ///                &lt;term&gt;interface&lt;/term&gt;
        ///                &lt;transacGrp&gt;
        ///                    &lt;transac type=&quot;origination&quot;&gt;poweruser&lt;/transac&gt;
        ///                    &lt;date&gt;2006-12-08T00:00:00&lt;/date&gt;
        ///                &lt;/transacGrp&gt;
        ///                &lt;transacGrp&gt;
        ///                    &lt;transac type=&quot;modification&quot;&gt;poweruser&lt;/transac&gt;
        ///                    &lt;date&gt;2006-12-08T00:00:00&lt;/date&gt;
        ///                &lt;/transacGrp&gt;
        ///                &lt;descripGrp&gt;
        ///                    &lt;descrip type=&quot;Part of Speech&quot;&gt;noun&lt;/descr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string termSec {
            get {
                return ResourceManager.GetString("termSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;transacGrp&gt;
        ///					&lt;transac type=&quot;transactionType&quot;&gt;origination&lt;/transac&gt;
        ///			&lt;/transacGrp&gt;.
        /// </summary>
        internal static string transac_toGroupify {
            get {
                return ResourceManager.GetString("transac_toGroupify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;transacGrp&gt;
        ///            &lt;transac type=&quot;origination&quot;&gt;tester&lt;/transac&gt;
        ///            &lt;date&gt;2009-05-05T00:00:00&lt;/date&gt;
        ///        &lt;/transacGrp&gt;.
        /// </summary>
        internal static string transacGrp {
            get {
                return ResourceManager.GetString("transacGrp", resourceCulture);
            }
        }
    }
}
