//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBXTools.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConversionAPI_MTF_TBXHandlersResourcesSources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConversionAPI_MTF_TBXHandlersResourcesSources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TBXTools.Test.ConversionAPI.MTF.TBXHandlersResourcesSources", typeof(ConversionAPI_MTF_TBXHandlersResourcesSources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;conceptEntry id=&quot;_2&quot;&gt;
        ///				&lt;transacGrp&gt;
        ///					&lt;transac type=&quot;transactionType&quot;&gt;origination&lt;/transac&gt;
        ///					&lt;transacNote type=&quot;responsibility&quot;&gt;mwetzel&lt;/transacNote&gt;
        ///					&lt;date&gt;2009-05-05&lt;/date&gt;
        ///				&lt;/transacGrp&gt;
        ///				&lt;transacGrp&gt;
        ///					&lt;transac type=&quot;transactionType&quot;&gt;modification&lt;/transac&gt;
        ///					&lt;transacNote type=&quot;responsibility&quot;&gt;mwetzel&lt;/transacNote&gt;
        ///					&lt;date&gt;2009-05-05&lt;/date&gt;
        ///				&lt;/transacGrp&gt;
        ///				&lt;langSec xml:lang=&quot;DE&quot;&gt;
        ///					&lt;termSec&gt;
        ///						&lt;term&gt;Schnittstelle&lt;/term&gt;
        ///						&lt;transacGrp&gt;
        ///							&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string conceptEntry {
            get {
                return ResourceManager.GetString("conceptEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;date&gt;2009-05-05&lt;/date&gt;.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;descrip type=&quot;subjectField&quot;&gt;security services;European Commission&lt;/descrip&gt;.
        /// </summary>
        internal static string descrip {
            get {
                return ResourceManager.GetString("descrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;langSec xml:lang=&quot;EN&quot;&gt;
        ///					&lt;termSec&gt;
        ///						&lt;term&gt;interface&lt;/term&gt;
        ///						&lt;termNote type=&quot;partOfSpeech&quot;&gt;noun&lt;/termNote&gt;
        ///						&lt;transacGrp&gt;
        ///							&lt;transac type=&quot;transactionType&quot;&gt;origination&lt;/transac&gt;
        ///							&lt;transacNote type=&quot;responsibility&quot;&gt;poweruser&lt;/transacNote&gt;
        ///							&lt;date&gt;2006-12-08&lt;/date&gt;
        ///						&lt;/transacGrp&gt;
        ///						&lt;transacGrp&gt;
        ///							&lt;transac type=&quot;transactionType&quot;&gt;modification&lt;/transac&gt;
        ///							&lt;transacNote type=&quot;responsibility&quot;&gt;poweruser&lt;/transacNote&gt;
        ///							&lt;date&gt;2006-12-08&lt;/date&gt;
        ///				 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string langSec {
            get {
                return ResourceManager.GetString("langSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;note&gt;Another name for an open star cluster. They are often
        ///                        termed Galactic Clusters because they are found mainly in the plane of our
        ///                        galaxy. If you were to view our galaxy from afar, you would find that all
        ///                        the open/galactic clusters lie within the spiral arms of the
        ///                        galaxy.&lt;/note&gt;.
        /// </summary>
        internal static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;term&gt;méthodologie prouvée&lt;/term&gt;.
        /// </summary>
        internal static string term {
            get {
                return ResourceManager.GetString("term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;termNote type=&quot;partOfSpeech&quot;&gt;noun&lt;/termNote&gt;.
        /// </summary>
        internal static string termNote {
            get {
                return ResourceManager.GetString("termNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;termNote type=&quot;partOfSpeech&quot;&gt;noun&lt;/termNote&gt;.
        /// </summary>
        internal static string termNote_toGroupify {
            get {
                return ResourceManager.GetString("termNote_toGroupify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;termSec&gt;
        ///						&lt;term&gt;interface&lt;/term&gt;
        ///						&lt;termNote type=&quot;partOfSpeech&quot;&gt;noun&lt;/termNote&gt;
        ///						&lt;transacGrp&gt;
        ///							&lt;transac type=&quot;transactionType&quot;&gt;origination&lt;/transac&gt;
        ///							&lt;transacNote type=&quot;responsibility&quot;&gt;poweruser&lt;/transacNote&gt;
        ///							&lt;date&gt;2006-12-08&lt;/date&gt;
        ///						&lt;/transacGrp&gt;
        ///						&lt;transacGrp&gt;
        ///							&lt;transac type=&quot;transactionType&quot;&gt;modification&lt;/transac&gt;
        ///							&lt;transacNote type=&quot;responsibility&quot;&gt;poweruser&lt;/transacNote&gt;
        ///							&lt;date&gt;2006-12-08&lt;/date&gt;
        ///						&lt;/transacGrp&gt;
        ///					&lt;/termSe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string termSec {
            get {
                return ResourceManager.GetString("termSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;transac type=&quot;transactionType&quot;&gt;origination&lt;/transac&gt;.
        /// </summary>
        internal static string transac_toGroupify {
            get {
                return ResourceManager.GetString("transac_toGroupify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;transacGrp&gt;
        ///					&lt;transac type=&quot;transactionType&quot;&gt;origination&lt;/transac&gt;
        ///					&lt;transacNote type=&quot;responsibility&quot;&gt;tester&lt;/transacNote&gt;
        ///					&lt;date&gt;2009-05-05&lt;/date&gt;
        ///				&lt;/transacGrp&gt;.
        /// </summary>
        internal static string transacGrp {
            get {
                return ResourceManager.GetString("transacGrp", resourceCulture);
            }
        }
    }
}
