//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBXTools.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TBXTools.Test.TestFiles", typeof(TestFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;mtf&gt;
        ///    &lt;conceptGrp&gt;
        ///        &lt;concept&gt;1&lt;/concept&gt;
        ///        &lt;transacGrp&gt;
        ///            &lt;transac type=&quot;origination&quot;&gt;mwetzel&lt;/transac&gt;
        ///            &lt;date&gt;2009-05-05T00:00:00&lt;/date&gt;
        ///        &lt;/transacGrp&gt;
        ///        &lt;transacGrp&gt;
        ///            &lt;transac type=&quot;modification&quot;&gt;mwetzel&lt;/transac&gt;
        ///            &lt;date&gt;2009-05-05T00:00:00&lt;/date&gt;
        ///        &lt;/transacGrp&gt;
        ///        &lt;languageGrp&gt;
        ///            &lt;language type=&quot;German&quot; lang=&quot;DE&quot; /&gt;
        ///            &lt;termGrp&gt;
        ///                &lt;term&gt;Schnittstelle [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MTF_Valid {
            get {
                return ResourceManager.GetString("MTF_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;?xml-model href=&quot;https://raw.githubusercontent.com/LTAC-Global/TBX-Basic_dialect/master/DCA/TBX-Basic_DCA.sch&quot; type=&quot;application/xml&quot; schematypens=&quot;http://purl.oclc.org/dsdl/schematron&quot;?&gt;
        ///&lt;?xml-model href=&quot;https://raw.githubusercontent.com/LTAC-Global/TBX-Basic_dialect/master/DCA/TBXcoreStructV03_TBX-Basic_integrated.rng&quot; type=&quot;application/xml&quot; schematypens=&quot;http://relaxng.org/ns/structure/1.0&quot;?&gt;
        ///&lt;tbx style=&quot;dca&quot; type=&quot;TBX-Basic&quot; xml:lang=&quot;en&quot; xmlns=&quot;urn:iso:std:is [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TBX_Valid {
            get {
                return ResourceManager.GetString("TBX_Valid", resourceCulture);
            }
        }
    }
}
